config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  root to: 'static_pages#home'
  get    'signup', to: 'users#new'
  get    'login' , to: 'sessions#new'
  post   'login' , to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :textboxes
end

app/models/textbox.rb
class Textbox < ActiveRecord::Base
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
     before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
 has_secure_password
 has_many :textboxes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def home
    @textbox = current_user.textboxes.build if logged_in?
  end
end

app/controllers/textboxes_controller.rb
class TextboxesController < ApplicationController
  before_action :logged_in_user, only: [:create]

  def create
      @textbox = current_user.textboxes.build(textbox_params)
      if @textbox.save
          flash[:success] = "Take Pic!"
          redirect_to root_url
      else
          render 'static_pages/home'
      end
  end

     private

     def textbox_params
         params.require(:textbox).permit(:content)
     end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @textboxes = @user.textboxes.order(created_at: :desc)
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to the Kasya Kasya!"
    redirect_to @user
  else
    render 'new'
    end
  end

   def edit
  end

  def update
    if @user.update(user_params)
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      render 'edit'
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                  :password_confirmation)
  end


 def set_message
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = { size: 80 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
      <%= link_to "Kasya kasya" , root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <% if logged_in? %>
        <li><%= link_to "ホーム", root_path %></li>
          <li><%= link_to "ユーザー", '#' %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              アカウント <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "プロフィール", current_user %></li>
              <li><%= link_to "設定", '#' %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "ログアウト", logout_path, method: "delete" %>
              </li>
            </ul>
              </li>
              <% else %>
          <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kasya Kasya</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
 <%= render 'layouts/header' %>
    <div class="container">
    <% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
<%= yield %>
    </div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_textbox_form.html.erb
<%= form_for(@textbox) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new picture..." %>
  </div>
  <%= f.submit "kasya", class: "btn btn-primary" %>
<% end %>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h2><%= current_user.name %></h2>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.textboxes.count, "Kasya") %></span>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="container">
     <h4 span style="color:black">Picture</h4>
  </div><hr />
<div class="row">
    <aside class="col-md-6">
      <section class="user_info">
         <%= render 'shared/user_info' %>
      </section>
      <section class="textbox_form">
        <%= render 'shared/textbox_form' %>
      </section>
    </aside>
  </div>

  <% else %>
  <div class="center jumbotron">
    <h1 span style="color:white">Welcome to the Kasyatter</h1>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/textboxes/_textbox.html.erb
<li id="textbox-<%= textbox.id %>">
  <%= link_to gravatar_for(textbox.user, size: 50), textbox.user %>
  <span class="user"><%= link_to textbox.user.name, textbox.user %></span>
  <span class="content"><%= textbox.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(textbox.created_at) %> ago.
  </span>
</li>

app/views/users/new.html.erb
<h1>新規登録</h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
      <%= form_for(@user)do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :名前 %>
      <%= f.text_field :name, class: 'form-control' %><br />

      <%= f.label :メールアドレス %>
      <%= f.text_field :email, class: 'form-control'  %><br />

      <%= f.label :パスワード %>
      <%= f.password_field :password, class: 'form-control'  %><br />

      <%= f.label :password_confirmation, "確認" %>
      <%= f.password_field :password_confirmation, class: 'form-control'  %><br />

      <%= f.submit "アカウント作成", class: "btn btn-sm btn-primary" %>
  <% end %>
  </div>
 </div>

app/views/users/show.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
  <h2>
  <%= gravatar_for @user %>
  <%= @user.name %>
   </h2>
 </section>
  </aside>
  <div class="col-md-8">
    <% if @user.textboxes.any? %>
      <h3>Picture (<%= @user.textboxes.count %>)</h3>
      <ol class="textboxes">
        <%= render partial: 'textboxes/textbox', collection: @textboxes %>
      </ol>
    <% end %>
  </div>
</div>